#!/bin/bash

# クラスターの選択
echo "利用可能なクラスター:"
clusters=$(aws ecs list-clusters --output text --query 'clusterArns[*]')
select cluster in $clusters
do
    if [ -n "$cluster" ]; then
        echo "選択されたクラスター: $cluster"
        break
    else
        echo "有効なクラスターを選択してください。"
    fi
done

# サービスの選択
echo "利用可能なサービス:"
services=$(aws ecs list-services --cluster $cluster --output text --query 'serviceArns[*]')
select service in $services
do
    if [ -n "$service" ]; then
        echo "選択されたサービス: $service"
        break
    else
        echo "有効なサービスを選択してください。"
    fi
done

# タスクの選択
echo "利用可能なタスク:"
task_arns=$(aws ecs list-tasks --cluster $cluster --service-name $service --output text --query 'taskArns[*]')
tasks=$(aws ecs describe-tasks --tasks $task_arns --cluster $cluster --output json)
task_ids=$(echo $tasks | jq -r '.tasks[].taskArn' | awk -F'/' '{print $NF}')
select task in $task_ids
do
    if [ -n "$task" ]; then
        echo "選択されたタスク: $task"
        break
    else
        echo "有効なタスクを選択してください。"
    fi
done

# コンテナの選択
echo "利用可能なコンテナ:"
containers=$(aws ecs describe-tasks --tasks $task --cluster $cluster --output json | jq -r '.tasks[].containers[].name')
select container in $containers
do
    if [ -n "$container" ]; then
        echo "選択されたコンテナ: $container"
        break
    else
        echo "有効なコンテナを選択してください。"
    fi
done

# ECS EXECの実行
echo "ECS EXECを実行中..."
aws ecs execute-command --cluster $cluster --task $task --container $container --interactive --command "/bin/bash"
